# -*- coding: utf-8 -*-
"""p2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6CeFI_5j5YUYbwhNY0OwLa_Vfg8Bdwe
"""

# Input
nama = input("Masukkan nama: ")
umur = int(input("Masukkan umur: "))

# Output
print("Halo", nama)
print("Umur Anda:", umur, "tahun")
print(f"Tahun lahir Anda: {2025 - umur}")  # f-string

# Input dari pengguna
panjang = float(input("Masukkan panjang: "))
lebar = float(input("Masukkan lebar: "))

# Perhitungan
luas = panjang * lebar
keliling = 2 * (panjang + lebar)

# Output hasil
print(f"Luas persegi panjang: {luas}")
print(f"Keliling persegi panjang: {keliling}")

jari = int(input("Jari-jari : "))
diameter = int(input("Diameter : "))

print("Luas = ", (3.14*jari)**2)
print("Keliling = ", 2*3.14*jari)