# -*- coding: utf-8 -*-
"""P2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168nDW7pF4Fp5OL05m2sCSzqgOozfWL0u
"""

# Input dari pengguna

panjang = float(input("Masukkan panjang: "))

lebar = float(input("Masukkan lebar: "))

# Perhitungan

luas = panjang * lebar

keliling = 2 * (panjang + lebar)

# Output hasil

print(f"Luas persegi panjang: {luas}")

print(f"Keliling persegi panjang: {keliling}")

# input dari pengguna

jari2 = float(input("jari2 lingkaran: "))
luas = 3.14 * jari2 * jari2
keliling = 2 * 3.14 * jari2
print(f"luas lingkaran: {luas}")
print(f"keliling lingkaran: {keliling}")

import math

def hitung_segitiga():
    print("\n=== Hitung Luas dan Keliling Segitiga (Rumus Heron) ===")

    # Input panjang sisi segitiga
    a = float(input("Masukkan panjang sisi a: "))
    b = float(input("Masukkan panjang sisi b: "))
    c = float(input("Masukkan panjang sisi c: "))

    # Cek apakah sisi membentuk segitiga valid
    if a + b > c and a + c > b and b + c > a:
        keliling = a + b + c
        s = keliling / 2  # setengah keliling
        luas = math.sqrt(s * (s - a) * (s - b) * (s - c))

        print(f"\nKeliling segitiga: {keliling}")
        print(f"Luas segitiga (rumus Heron): {luas}")
    else:
        print("Sisi-sisi tersebut tidak membentuk segitiga yang valid.")

if __name__ == "__main__":
    hitung_segitiga()

sisi1 = int(input("Sisi 1 : "))
sisi2 = int(input("Sisi 2 : "))
sisi3 = int(input("Sisi 3 : "))
tinggi = int(input("Tinggi : "))

luas = (sisi1+sisi2) * tinggi / 2
keliling = sisi1+sisi2+sisi3+tinggi

print("Luas = ", luas)
print("Keliling =", keliling)

def kalkulator_operasi_dasar():
    print("=== Kalkulator Operasi Dasar ===")
    try:
        angka1 = float(input("Masukkan angka pertama: "))
        operator = input("Masukkan operator (+, -, *, /): ")
        angka2 = float(input("Masukkan angka kedua: "))

        if operator == '+':
            hasil = angka1 + angka2
        elif operator == '-':
            hasil = angka1 - angka2
        elif operator == '*':
            hasil = angka1 * angka2
        elif operator == '/':
            if angka2 == 0:
                print("Kesalahan: Tidak bisa membagi dengan nol.")
                return
            hasil = angka1 / angka2
        else:
            print("Operator tidak dikenali. Gunakan +, -, *, atau /.")
            return

        print(f"Hasil: {hasil}")

    except ValueError:
        print("Input tidak valid. Harap masukkan angka yang benar.")

# Jalankan fungsi
kalkulator_operasi_dasar()

import math

def kalkulator_pangkat_akar():
    print("=== Kalkulator Perpangkatan dan Akar Kuadrat ===")
    print("1. Perpangkatan (x^y)")
    print("2. Akar Kuadrat (√x)")
    pilihan = input("Pilih menu (1/2): ")

    if pilihan == "1":
        x = float(input("Masukkan angka dasar (x): "))
        y = float(input("Masukkan pangkat (y): "))
        hasil = x ** y
        print(f"Hasil dari {x}^{y} = {hasil}")

    elif pilihan == "2":
        x = float(input("Masukkan angka yang akan diakar: "))
        if x < 0:
            print("Tidak dapat menghitung akar dari bilangan negatif dalam real.")
        else:
            hasil = math.sqrt(x)
            print(f"Hasil akar kuadrat dari √{x} = {hasil}")

    else:
        print("Pilihan tidak valid.")

# Jalankan program
kalkulator_pangkat_akar()

def konversi_suhu():
    print("=== Kalkulator Konversi Suhu ===")
    print("1. Celsius ke Fahrenheit dan Kelvin")
    print("2. Fahrenheit ke Celsius dan Kelvin")
    print("3. Kelvin ke Celsius dan Fahrenheit")

    pilihan = input("Pilih konversi (1/2/3): ")

    if pilihan == "1":
        c = float(input("Masukkan suhu dalam Celsius: "))
        f = (c * 9/5) + 32
        k = c + 273.15
        print(f"\nHasil Konversi:")
        print(f"{c}°C = {f:.2f}°F = {k:.2f}K")

    elif pilihan == "2":
        f = float(input("Masukkan suhu dalam Fahrenheit: "))
        c = (f - 32) * 5/9
        k = c + 273.15
        print(f"\nHasil Konversi:")
        print(f"{f}°F = {c:.2f}°C = {k:.2f}K")

    elif pilihan == "3":
        k = float(input("Masukkan suhu dalam Kelvin: "))
        c = k - 273.15
        f = (c * 9/5) + 32
        print(f"\nHasil Konversi:")
        print(f"{k}K = {c:.2f}°C = {f:.2f}°F")

    else:
        print("Pilihan tidak valid.")

# Jalankan program
konversi_suhu()

# sistem akademik sederhana

Data                   Tipe Data
-----------------------------------
NIM                   | String
Nama Mahasiswa        | String
Tanggal Lahir         | Date
Email                 | String
Nomor Telepon         | String
Mata Kuliah           | String
Nilai                 | Float/Int
Semester              | Int
Status Mahasiswa      | Enum

# sistem Aplikasi E-commerce

Data                   Tipe Data
-----------------------------------
ID Produk             | String / Int
Nama Produk           | String
Harga                 | Float
Stok                  | Int
Kategori              | String
ID Pengguna           | String / Int
Alamat Pengiriman     | String
Tanggal Transaksi     | DateTime
Status Pembayaran     | Enum

# sistem Reservasi Hotel

Data                   Tipe Data
------------------------------------
ID Reservasi          | String / Int
Nama Tamu             | String
Nomor Identitas       | String
Tanggal Check-in/out  | Date
Jenis & Nomor Kamar   | String / Int
Jumlah Tamu           | Int
Total Biaya           | Float
Status Reservasi      | Enum