# -*- coding: utf-8 -*-
"""p4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cs281B5buROFQFCQ_Oq3XfKkUBnZ-uba
"""

def fibonacci(n) :
  # Membuat list kososng untuk menyimpan deret fibonacci
  fib_series = []

  # dua angka pertama dalam deret fibonacci
  a, b = 0, 1

  # perulangan sebanyak n kali
  for _ in range(n) :
    #tambahkan angka saat ini ke dalam list
    fib_series.append(a)
     # Perbarui nilai a dan b untuk langkah berikutnya
    a, b = b, a + b

  return fib_series

# Program utama
print("=== Deret Fibonacci ===")
n = int(input("Masukkan jumlah angka dalam deret fibonacci:"))

# Cek agar input valid
if n <= 0:
  print("Masukkan angka lebih dari 0.")
else:
  hasil = fibonacci(n)
  print("Deret fibonacci:")
  print(hasil)

# Meminta jumlah baris dari pengguna
n = int(input("Masukkan jumlah baris segitiga: "))

# Loop untuk setiap baris
for i in range(1, n + 1):
    # Cetak i buah asterisk di setiap baris
    print('*' * i)